const {chromium}=require('C:/Users/cumc910208132/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1100}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:5173');await page.locator('#sync-status').waitFor();
assert.equal(await page.locator('.item').count(),0);await page.locator('#item-name').fill('aguacate');await page.locator('.search-result').filter({hasText:'Aguacate'}).first().click();await page.locator('.item').first().waitFor();assert.equal(await page.locator('.item-emoji').first().textContent(),'🥑');
await page.locator('#item-name').fill('chiles');await page.locator('.search-result').filter({hasText:'Chiles'}).first().click();await page.waitForFunction(()=>document.querySelectorAll('.item').length===2);assert.equal(await page.locator('.item').filter({has:page.locator('strong').filter({hasText:/^Chiles$/})}).locator('.item-emoji').textContent(),'🌶️');
await page.locator('#item-name').fill('Salsa de la abuela');await page.locator('.create-result').click();await page.locator('#product-category').selectOption('Chiles secos, salsas y aderezos');await page.locator('#save-product').click();await page.locator('#workspace-dialog').waitFor({state:'hidden'});assert.equal(await page.locator('.item').count(),3);assert.equal(await page.locator('.item').filter({hasText:'Salsa de la abuela'}).locator('.item-emoji').textContent(),'🫙');
await page.getByRole('button',{name:'Cambiar icono de Chiles',exact:true}).click();await page.locator('#product-quantity').fill('0.5');await page.getByLabel('Unidad de compra',{exact:true}).selectOption('kilogram');await page.getByLabel('Notas',{exact:true}).fill('Verdes');await page.locator('#save-product').click();await page.locator('#workspace-dialog').waitFor({state:'hidden'});assert.match(await page.locator('.item').filter({has:page.locator('strong').filter({hasText:/^Chiles$/})}).textContent(),/0.5 kg/);
await page.locator('.item').filter({has:page.locator('strong').filter({hasText:/^Chiles$/})}).locator('.check').click();await page.locator('#purchase-price').fill('20');await page.locator('#purchase-store').fill('Mercado');await page.getByRole('button',{name:'Guardar compra',exact:true}).click();await page.locator('#workspace-dialog').waitFor({state:'hidden'});await page.locator('#toast').getByRole('button',{name:'Deshacer'}).click();await page.waitForFunction(()=>!document.querySelectorAll('.item input:checked').length);
await page.locator('#theme-toggle').click();await page.waitForFunction(()=>document.documentElement.dataset.theme==='dark');await page.reload();await page.locator('#sync-status').waitFor();assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');assert.equal(await page.locator('.item').count(),3);
await page.getByRole('button',{name:'Dictar o pegar lista',exact:false}).click();await page.getByLabel('Transcripción editable').fill('Agrega dos kilos de papa, medio kilo de tomate rojo, una docena de huevos y dos leches deslactosadas de un litro');await page.getByRole('button',{name:'Revisar productos',exact:true}).click();assert.equal(await page.locator('.draft-row').count(),4);await page.getByRole('button',{name:'Agregar seleccionados'}).click();await page.locator('#workspace-dialog').waitFor({state:'hidden'});assert.equal(await page.locator('.item').count(),7);
await page.locator('#new-list').click();await page.locator('#list-name').fill('Fiesta');await page.locator('#save-list').click();await page.locator('#workspace-dialog').waitFor({state:'hidden'});assert.equal(await page.locator('.item').count(),0);await page.locator('#list-select').selectOption({label:'Mi compra semanal'});await page.locator('.item').first().waitFor();
await page.locator('.sidebar [data-view=catalog]').click();await page.getByLabel('Buscar en catálogo').fill('Salsa de la abuela');assert.equal(await page.locator('.catalog-product').count(),1);await page.locator('.sidebar [data-view=lists]').click();await page.screenshot({path:'preview-dark.png',fullPage:true});await page.locator('#theme-toggle').click();await page.waitForFunction(()=>document.documentElement.dataset.theme==='light');await page.screenshot({path:'preview-light.png',fullPage:true});
for(const width of [360,390,430,768,1024,1280,1440]){await page.setViewportSize({width,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'overflow '+width);}await page.setViewportSize({width:390,height:844});await page.screenshot({path:'preview-mobile.png',fullPage:true});
await page.evaluate(()=>navigator.serviceWorker.ready);await page.reload();await page.locator('#sync-status').waitFor();await context.setOffline(true);await page.reload();await page.locator('#sync-status').waitFor();assert.match(await page.locator('#sync-status').textContent(),/Sin conexión/);await page.locator('#item-name').fill('manzana');await page.locator('.search-result').first().click();await page.waitForFunction(()=>document.querySelectorAll('.item').length===8);await context.setOffline(false);
assert.deepEqual(errors,[]);console.log('PASS: iconos por producto, categorías, producto propio, detalles, deshacer, persistencia, temas, captura múltiple, listas, catálogo propio, 7 tamaños, offline real.');await browser.close();})().catch(e=>{console.error(e);process.exit(1);});

