const fs=require('node:fs');
const source=process.argv[2]||'data/catalog-source.txt';
if(!source)throw Error('Uso: node scripts/build-catalog.cjs ruta-al-prompt.txt');
const text=fs.readFileSync(source,'utf8');
const blocks=[...text.matchAll(/^20\.(\d+) ([^\r\n]+)\r?\n([\s\S]*?)(?=^20\.\d+ |^Reglas del seed)/gm)];
const expansions={
9:'Leche entera, leche semidescremada, leche descremada, leche deslactosada, leche evaporada, leche condensada, leche en polvo, crema, media crema, crema para batir, mantequilla, yogur natural, yogur griego, yogur bebible, kéfir, jocoque, huevo de gallina, huevo de codorniz, claras de huevo, bebida de soya, bebida de almendra, bebida de avena, bebida de coco, bebida de arroz, yogur vegetal, crema vegetal',
10:'Queso panela, queso fresco, queso Oaxaca, queso asadero, queso Chihuahua, queso manchego, queso mozzarella, queso cheddar, queso gouda, queso parmesano, queso cotija, queso crema, requesón, ricotta, cottage, queso de cabra, queso azul',
11:'Bolillo, telera, baguette, pan de caja blanco, pan integral, pan multigrano, pan para hamburguesa, pan para hot dog, pan pita, bagel, croissant, concha, muffin, dona, pan tostado, tortilla de maíz, tortilla de harina, tortilla integral, tostada, totopo',
12:'Arroz blanco, arroz integral, arroz basmati, arroz para sushi, avena, quinoa, amaranto, cebada, cereal de maíz, cereal integral, granola, espagueti, fideo, macarrón, codito, penne, fusilli, pasta para lasaña, pasta integral, fideo de arroz, harina de trigo, harina integral, harina de maíz, harina de arroz, harina de avena, harina de almendra',
13:'Frijol pinto, frijol negro, frijol bayo, frijol peruano, frijol rojo, lenteja, garbanzo, haba seca, alubia, soya, frijol refrito, frijol cocido, lenteja cocida',
15:'Aceite de oliva, aceite de canola, aceite de girasol, aceite de maíz, aceite de aguacate, aceite de coco, aceite de ajonjolí, vinagre blanco, vinagre de manzana, vinagre balsámico, vinagre de vino, vinagre de arroz, margarina, manteca vegetal, aceite en aerosol',
16:'Sal de mesa, sal de grano, pimienta negra, pimienta blanca, pimienta rosa, comino, orégano, canela en rama, canela molida, clavo, laurel, tomillo seco, romero seco, albahaca seca, paprika, pimentón ahumado, cúrcuma, curry, jengibre molido, nuez moscada, anís estrella, cardamomo, azafrán, ajo en polvo, cebolla en polvo, chile piquín, hojuelas de chile, sazonador para pollo, sazonador para carne, consomé en polvo',
17:'Chile ancho, chile guajillo, chile pasilla, chile morita, chile cascabel, chile chipotle, chile de árbol seco, salsa verde, salsa roja, salsa picante, salsa de tomate, puré de tomate, cátsup, mostaza, mayonesa, salsa de soya, salsa inglesa, salsa barbecue, salsa teriyaki, salsa de ostión, pesto, mole, adobo, aderezo ranch, aderezo César, aderezo italiano, vinagreta',
19:'Azúcar blanca, azúcar mascabado, azúcar glass, piloncillo, miel, miel de agave, jarabe de maple, stevia, edulcorante, cocoa, chocolate para hornear, chispa de chocolate, vainilla, polvo para hornear, bicarbonato, levadura, fécula de maíz, grenetina, gelatina en polvo, fondant, colorante alimentario, granillo, decoración comestible',
20:'Café molido, café en grano, café soluble, café descafeinado, cápsula de café, té negro, té verde, té blanco, té chai, manzanilla, jamaica, hierbabuena, tila, infusión de jengibre, matcha, chocolate en polvo, crema para café',
21:'Agua natural, agua mineral, agua saborizada, refresco, jugo de naranja, jugo de manzana, jugo de uva, néctar, agua de coco, bebida isotónica, bebida energética, cerveza, cerveza sin alcohol, vino tinto, vino blanco, vino rosado, sidra, hielo',
3:'Chile jalapeño, chile serrano, chile poblano, chile habanero, chile de árbol fresco, chile güero, chile chilaca, chile morrón rojo, chile morrón verde, chile morrón amarillo, cilantro, perejil, epazote, hierbabuena, menta, albahaca, romero fresco, tomillo fresco, eneldo fresco',
5:'Carne molida de cerdo, chuleta de cerdo, lomo de cerdo, pierna de cerdo, espaldilla de cerdo, costilla de cerdo, panceta, tocino fresco, carne para carnitas, carne para pastor, chicharrón, manteca de cerdo',
6:'Pollo entero, pechuga con hueso, pechuga sin hueso, muslo de pollo, pierna de pollo, alas de pollo, fajitas de pollo, milanesa de pollo, pollo molido, menudencias de pollo, pavo entero, pechuga de pavo, pavo molido'
};
const norm=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s+/g,' ').trim();
const aliases={aguacate:['aguacates'],jitomate:['tomate','tomates','tomate rojo','tomates rojos'],platano:['plátanos','banana','bananas'],'leche entera':['leche','leches'],'bebida de almendra':['leche de almendra'],'huevo de gallina':['huevo','huevos'],papa:['papas','patata'],elote:['maíz tierno'],ejote:['judía verde'],chicharo:['guisante'],toronja:['pomelo'],camote:['batata'],calabacita:['zucchini'],'chile morron rojo':['pimiento rojo'],'chile jalapeno':['jalapeño','jalapeños'],'pan integral':['pan de caja integral']};
const categories=[],products=[],seen=new Map();
for(const [,num,title,body]of blocks){const id='cat-'+num;categories.push({id,name:title});const first=body.split(/\r?\n/)[0];const names=(expansions[num]||first.replace(/ y ([^,]+)\.$/,', $1')).replace(/\.$/,'').split(/,\s*/);for(let name of names){name=name.trim();if(!name)continue;name=name[0].toUpperCase()+name.slice(1);const key=norm(name);if(seen.has(key))continue;const p={id:'p-'+key.replace(/[^a-z0-9]+/g,'-'),name,category:title,aliases:aliases[key]||[],unit:'piece'};products.push(p);seen.set(key,p);}}
for(const name of ['Chiles','Pan','Sal y pimienta']){products.push({id:'p-'+norm(name).replaceAll(' ','-'),name,category:name==='Chiles'?categories[2].name:name==='Pan'?categories[10].name:categories[15].name,aliases:name==='Chiles'?['chile']:[],unit:'piece'});}
fs.mkdirSync('data',{recursive:true});fs.writeFileSync('data/catalog.json',JSON.stringify({categories,products},null,2));fs.mkdirSync('docs',{recursive:true});fs.writeFileSync('docs/catalog-report.md','# Catálogo reproducible\n\n'+products.length+' productos únicos en '+categories.length+' categorías.\n\n'+categories.map(c=>'- '+c.name+': '+products.filter(p=>p.category===c.name).length).join('\n')+'\n\nLos iconos exactos o relacionados se asignan por nombre de producto en src/catalog.js. Los productos sin equivalencia tienen iniciales, nunca el icono de su categoría.\n');console.log(products.length+' productos / '+categories.length+' categorías');
