import {semanticPlan,approvedIcon,ICON_COLLECTIONS} from './icon-semantics.js';
import {cached,cache} from './icon-cache.js';
const API='https://api.iconify.design',TTL=7*24*60*60*1000;
const abort=signal=>{if(signal?.aborted)throw new DOMException('Cancelado','AbortError');};
async function request(url,signal,options={}){const controller=new AbortController(),cancel=()=>controller.abort();signal?.addEventListener('abort',cancel,{once:true});const timeout=setTimeout(cancel,10000);try{abort(signal);const r=await fetch(url,{...options,signal:controller.signal});if(!r.ok)throw Error('HTTP_'+r.status);return r;}finally{clearTimeout(timeout);signal?.removeEventListener('abort',cancel);}}
async function searchTerm(term,signal){const key='search:lucide,tabler:'+term,stored=await cached(key);abort(signal);if(stored&&(Date.now()-stored.cachedAt<TTL||!navigator.onLine))return {...stored,fromCache:true};try{const params=new URLSearchParams({query:term,limit:'24',prefixes:Object.keys(ICON_COLLECTIONS).join(',')});const data=await (await request(API+'/search?'+params,signal)).json();abort(signal);if(!Array.isArray(data.icons))throw Error('INVALID_RESPONSE');const icons=[...new Set(data.icons.filter(approvedIcon))].sort((a,b)=>Object.keys(ICON_COLLECTIONS).indexOf(a.split(':')[0])-Object.keys(ICON_COLLECTIONS).indexOf(b.split(':')[0])).slice(0,24);const result={icons};await cache(key,result).catch(()=>{});return result;}catch(e){abort(signal);if(stored)return {...stored,fromCache:true,stale:true};throw e;}}
export async function searchIcons(text,category,language,signal){let plan=semanticPlan(text,category,language),translationState='';if(plan.unknown){const key='translation:'+text;let translated=await cached(key);if(!translated&&navigator.onLine){try{const r=await request('/api/icon-translation',signal,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})});const data=await r.json();if(typeof data.translation!=='string'||!/^[a-z0-9 -]{1,120}$/i.test(data.translation))throw Error('INVALID_TRANSLATION');translated={translation:data.translation.toLowerCase()};await cache(key,translated).catch(()=>{});}catch(e){abort(signal);translationState=e.message==='HTTP_503'?'unconfigured':'unavailable';}}if(translated){plan={...plan,queries:[translated.translation,...plan.alternatives],source:'service',unknown:false};translationState='translated';}else return {...plan,icons:[],translationState:translationState||'unavailable',terms:[]};}
 const icons=[],terms=[];let fromCache=false,partialError=false;for(const term of plan.queries){abort(signal);try{const r=await searchTerm(term,signal);terms.push(term);fromCache ||=!!r.fromCache;for(const key of r.icons)if(!icons.some(i=>i.key===key))icons.push({key,term});}catch(e){abort(signal);partialError=true;}if(icons.length>=24)break;}abort(signal);if(partialError&&!icons.length)throw Error('SEARCH_UNAVAILABLE');return {...plan,icons:icons.slice(0,24),terms,fromCache,partialError,translationState};}
// Parse only static outline geometry. Reject scripts, external references and event/style attributes.
export function sanitizeSVG(source){const doc=new DOMParser().parseFromString(source,'image/svg+xml'),root=doc.documentElement;if(root.localName!=='svg'||doc.querySelector('parsererror'))throw Error('INVALID_SVG');const tags=new Set(['svg','g','path','circle','ellipse','rect','line','polyline','polygon','title','desc']),attrs=new Set(['xmlns','viewBox','width','height','d','cx','cy','r','rx','ry','x','y','x1','x2','y1','y2','points','fill','stroke','stroke-width','stroke-linecap','stroke-linejoin','stroke-miterlimit','stroke-dasharray','stroke-dashoffset','fill-rule','clip-rule','opacity','fill-opacity','stroke-opacity','transform']);for(const node of [root,...root.querySelectorAll('*')]){if(!tags.has(node.localName)){node.remove();continue;}for(const attr of [...node.attributes]){if(!attrs.has(attr.name)||/url\s*\(|javascript:|https?:/i.test(attr.value)&&attr.name!=='xmlns')node.removeAttribute(attr.name);}}root.setAttribute('xmlns','http://www.w3.org/2000/svg');root.setAttribute('width','24');root.setAttribute('height','24');if(!root.hasAttribute('viewBox'))root.setAttribute('viewBox','0 0 24 24');return new XMLSerializer().serializeToString(root);}
export async function iconData(key,signal){if(!approvedIcon(key))throw Error('COLLECTION_NOT_ALLOWED');const stored=await cached('icon:'+key);abort(signal);if(stored?.svg)return {...stored,svg:sanitizeSVG(stored.svg)};const [prefix,name]=key.split(':');const source=await (await request(`${API}/${prefix}/${name}.svg`,signal)).text();abort(signal);if(source.length>100000)throw Error('INVALID_SVG');const data={icon_key:key,svg:sanitizeSVG(source),license:ICON_COLLECTIONS[prefix]};await cache('icon:'+key,data);return data;}
export function paintIcon(node,key,fallback='◇'){node.replaceChildren(document.createTextNode(fallback));node.dataset.iconKey=key||'';if(!key)return;iconData(key).then(data=>{if(node.dataset.iconKey!==key)return;const svg=new DOMParser().parseFromString(data.svg,'image/svg+xml').documentElement;svg.setAttribute('aria-hidden','true');svg.classList.add('daylist-icon');node.replaceChildren(document.importNode(svg,true));}).catch(()=>{node.title='Icono no disponible sin conexión; se conserva su identificador.';});}
export function iconNode(key,fallback='',className=''){const n=document.createElement('span');n.className=className;paintIcon(n,key,fallback);return n;}
