import {$,el,button,input,select,field} from './ui.js';
import {ICON_COLLECTIONS} from './icon-semantics.js';
import {searchIcons,iconData,paintIcon} from './icon-service.js';

export function createIconPicker({name='',category='',value=null,onConfirm}){
 const root=el('section','iconify-picker'),query=input(name,'Busca un producto o categoría…'),language=select({es:'Español',en:'Inglés (consulta directa)'},'es');
 query.maxLength=120;query.setAttribute('aria-label','Buscar icono en Iconify');language.setAttribute('aria-label','Idioma de búsqueda de iconos');
 const controls=el('div','iconify-controls');controls.append(query,language);const status=el('p','iconify-status');status.setAttribute('role','status');status.setAttribute('aria-live','polite');
 const terms=el('p','iconify-terms'),alternatives=el('div','iconify-alternatives'),grid=el('div','iconify-grid');grid.setAttribute('role','group');grid.setAttribute('aria-label','Resultados de iconos');
 const preview=el('div','iconify-selection'),symbol=el('span','iconify-preview'),selectedLabel=el('span','','Sin selección nueva');paintIcon(symbol,value,'◇');
 let controller,revision=0,timer,selected=null,confirmed=value,categoryName=category,disposed=false;
 const confirm=button('Confirmar icono',async()=>{const key=selected;if(!key)return;confirm.disabled=true;try{await iconData(key,controller?.signal);if(disposed||key!==selected)return;confirmed=key;onConfirm(key);selectedLabel.textContent=`Confirmado: ${key}. Guarda el formulario para aplicar.`;status.textContent='Icono confirmado y guardado en caché para uso offline.';}catch(e){if(e.name!=='AbortError')status.textContent='No pudimos guardar el icono offline. Vuelve a intentarlo.';}finally{confirm.disabled=!selected||selected===confirmed;}},'button primary');confirm.disabled=true;preview.append(symbol,selectedLabel,confirm);
 const retry=button('Reintentar búsqueda',()=>schedule(0),'text-button');retry.hidden=true;
 const licenses=el('details','iconify-licenses');licenses.append(el('summary','','Colecciones y licencias'));for(const c of Object.values(ICON_COLLECTIONS)){const a=el('a','',`${c.name} · ${c.license}`);a.href=c.url;a.target='_blank';a.rel='noopener noreferrer';licenses.append(a);}
 root.append(el('p','iconify-help','Busca en español, selecciona un resultado y confirma el icono. Puedes cambiarlo antes de guardar.'),controls,status,terms,alternatives,grid,retry,preview,licenses);
 function dispose(){disposed=true;clearTimeout(timer);controller?.abort();observer.disconnect();}
 const observer=new MutationObserver(()=>{if(!root.isConnected)dispose();});
 queueMicrotask(()=>{if(root.isConnected){observer.observe(document.body,{childList:true,subtree:true});root.closest('dialog')?.addEventListener('close',dispose,{once:true});}});
 function schedule(delay=350){clearTimeout(timer);controller?.abort();revision++;selected=null;confirm.disabled=true;grid.replaceChildren();alternatives.replaceChildren();terms.textContent='';retry.hidden=true;if(!query.value.trim()){status.textContent='Escribe un nombre para ver sugerencias.';return;}status.textContent='Preparando búsqueda…';timer=setTimeout(run,delay);}
 async function run(){if(disposed)return;const current=revision;controller=new AbortController();const {signal}=controller;grid.setAttribute('aria-busy','true');status.textContent='Buscando iconos…';try{const result=await searchIcons(query.value.trim(),categoryName,language.value,signal);if(disposed||current!==revision)return;terms.textContent=result.terms.length?`${result.source==='service'?'Traducción del servicio':'Búsqueda'}: ${result.terms.join(' → ')}`:'';
 if(result.unknown){status.textContent=result.translationState==='unconfigured'?'No conocemos este término y no hay traducción configurada. Corrige el nombre, busca en inglés o elige una alternativa.':'No se pudo traducir este término. Corrige la búsqueda, usa inglés o elige una alternativa.';}else status.textContent=result.icons.length?`${result.icons.length} iconos${result.fromCache?' · Caché local':''}${result.partialError?' · Algunos resultados no pudieron cargarse':''}. Selecciona uno para confirmarlo.`:'Sin coincidencias. Prueba otra palabra o una alternativa de categoría.';
 for(const term of result.alternatives||[]){alternatives.append(button(`Buscar «${term}»`,()=>{query.value=term;language.value='en';schedule();},'text-button'));}
 for(const {key,term}of result.icons){const tile=button('',()=>{selected=key;confirm.disabled=selected===confirmed;paintIcon(symbol,key);selectedLabel.textContent=`Seleccionado: ${key}`;for(const b of grid.querySelectorAll('button'))b.setAttribute('aria-pressed',String(b.dataset.key===key));},'iconify-choice');tile.dataset.key=key;tile.title=key;tile.setAttribute('aria-label',`Seleccionar ${key}`);tile.setAttribute('aria-pressed','false');tile.disabled=true;const icon=el('span','iconify-result-image'),label=el('span','',key.split(':')[1]);tile.append(icon,label,el('small','',ICON_COLLECTIONS[key.split(':')[0]].name));grid.append(tile);
 iconData(key,signal).then(data=>{if(disposed||current!==revision)return;const svg=new DOMParser().parseFromString(data.svg,'image/svg+xml').documentElement;svg.setAttribute('aria-hidden','true');svg.classList.add('daylist-icon');icon.append(document.importNode(svg,true));tile.disabled=false;}).catch(e=>{if(e.name==='AbortError')return;if(current!==revision||disposed)return;icon.textContent='—';tile.title='No se pudo cargar este icono';retry.hidden=false;});}
 }catch(e){if(e.name==='AbortError'||current!==revision||disposed)return;status.textContent=navigator.onLine?'No pudimos consultar Iconify. Reintenta o conserva el icono actual.':'Sin conexión y sin resultados guardados para esta búsqueda. Conserva el icono actual o busca uno usado anteriormente.';retry.hidden=false;}finally{if(current===revision)grid.setAttribute('aria-busy','false');}}
 query.oninput=()=>schedule();query.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();schedule(0);}});language.onchange=()=>schedule();root.updateContext=(nextName,nextCategory)=>{if(query.value===name){query.value=nextName;name=nextName;schedule();}categoryName=nextCategory;};root.hasPending=()=>!!selected&&selected!==confirmed;root.dispose=dispose;schedule();return root;
}
