import {$,el,button,input,select,field,empty,dialog} from './ui.js';
import {normalize,units} from './catalog.js';
import {iconNode} from './icon-service.js';
export const money=n=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(n/100);
export const purchaseKey=i=>JSON.stringify([i.productId||normalize(i.name),normalize(i.brand||''),normalize(i.variant||''),i.unit||'piece',Number(i.packageSize)||null,i.packageUnit||'']);
export const historyFor=(state,item)=>(state.purchases||[]).filter(p=>p.key===purchaseKey(item)).sort((a,b)=>b.at.localeCompare(a.at));
export const changeText=(now,before)=>{if(!before)return 'Primera compra registrada';const diff=now-before;return diff===0?'Sin cambio de precio':`${diff>0?'Subió':'Bajó'} ${money(Math.abs(diff))} (${(Math.abs(diff)/before*100).toFixed(1)} %) por unidad`;};
const date=p=>new Date(p.at).toLocaleDateString('es-MX');
export function purchaseDialog(api,item,listId){
 const {d,content}=dialog('Registrar compra'),form=el('form','purchase-form'),previous=historyFor(api.state(),item)[0];
 content.append(el('h3','',item.name),el('p','section-description','Registra lo que pagaste. Compara precios de la misma unidad, marca y presentación.'));
 if(previous){const last=el('div','purchase-previous');last.append(el('strong','',`Última compra: ${money(previous.unitCents)} / ${units[previous.unit]}`),el('p','',`${previous.store} · ${date(previous)}`));content.append(last);}else content.append(el('p','purchase-previous','Esta será tu primera referencia de precio para este producto.'));
 const price=input('','0.00','number'),qty=input(item.quantity||'1','','number'),store=input('','Ej. Mercado del barrio');price.min='0.01';price.max='9999999';price.step='.01';price.required=true;price.id='purchase-price';qty.min='.001';qty.max='999999';qty.step='.001';qty.required=true;store.required=true;store.maxLength=100;store.id='purchase-store';
 const stores=el('datalist');stores.id='purchase-stores';for(const name of new Set((api.state().purchases||[]).map(p=>p.store))){const o=el('option');o.value=name;stores.append(o);}store.setAttribute('list',stores.id);
 const grid=el('div','form-grid');grid.append(field(`Precio por ${units[item.unit||'piece']} (MXN)`,price),field(`Cantidad comprada (${units[item.unit||'piece']})`,qty));form.append(grid,field('Establecimiento',store),stores);
 const total=el('div','purchase-total'),delta=el('p','section-description'),error=el('p','form-error');error.setAttribute('role','alert');
 const draw=()=>{const cents=Math.round(Number(price.value)*100);total.textContent=`Total de esta compra: ${money(Math.round(cents*Number(qty.value)))}`;delta.textContent=cents?changeText(cents,previous?.unitCents):'';};price.oninput=qty.oninput=draw;draw();form.append(total,delta,error);
 const save=button('Guardar compra',null,'button primary');save.type='submit';form.append(el('p','section-description','Al volver a pendiente se anula el registro de esta compra. Retirar comprados conserva el historial.'),button('Cancelar',()=>d.close()),save);
 form.onsubmit=async e=>{e.preventDefault();if(!form.reportValidity()||!store.value.trim())return;const unitCents=Math.round(Number(price.value)*100),quantity=Number(qty.value),totalCents=Math.round(unitCents*quantity);if(!Number.isSafeInteger(totalCents)||totalCents<=0){error.textContent='Revisa el precio y la cantidad.';return;}save.disabled=true;const ok=await api.commit('Compra registrada',s=>{const l=s.lists.find(l=>l.id===listId),i=l?.items.find(i=>i.id===item.id);if(!i||i.done)throw Error('STALE');const p={id:crypto.randomUUID(),key:purchaseKey(i),productId:i.productId,name:i.name,emoji:i.emoji,icon_key:i.icon_key||null,brand:i.brand||'',variant:i.variant||'',packageSize:i.packageSize,packageUnit:i.packageUnit,unit:i.unit||'piece',quantity,unitCents,totalCents,store:store.value.trim().replace(/\s+/g,' '),at:new Date().toISOString(),listId,itemId:i.id};s.purchases??=[];s.purchases.push(p);i.done=true;i.purchaseId=p.id;i.purchasedAt=p.at;api.activity(l,`Compró ${i.name} · ${money(totalCents)} en ${p.store}`);},true);save.disabled=false;if(ok)d.close();};content.append(form);price.focus();
}
export function renderSpending(state,list,host){host.replaceChildren();const records=(state.purchases||[]).filter(p=>p.listId===list.id);host.append(el('small','','GASTO REGISTRADO · MXN'),el('strong','',money(records.reduce((n,p)=>n+p.totalCents,0))),el('p','',`${records.length} compras registradas en esta lista. Incluye productos retirados.`));}
export function renderCompare(api){
 const box=api.section('Compara','Tus compras, tus referencias. Descubre dónde compraste y cómo cambian los precios.'),records=api.state().purchases||[];
 if(!records.length){const intro=el('div','compare-empty');intro.append(el('span','compare-symbol','↗'),el('h3','','Tu primera compra inicia la comparación'),el('p','','Marca un producto como comprado y registra su precio y establecimiento. Aquí verás el historial, el último precio de cada tienda y si subió o bajó.'),button('Ir a mi lista',()=>api.goLists(),'button primary'));box.append(intro);const demo=el('article','compare-card compare-demo');demo.append(el('small','','EJEMPLO ILUSTRATIVO · NO SON PRECIOS REALES'),el('h3','','Leche · 1 litro'),el('p','','Mercado del barrio — $26.00'),el('p','','Supermercado — $29.00'),el('strong','','Diferencia: $3.00 por litro'),el('p','section-description','Tus productos aparecerán aquí después de registrar una compra.'));box.append(demo);return;}
 const search=input('','Buscar producto o establecimiento…'),sort=select({recent:'Más recientes',name:'Nombre del producto'},'recent'),tools=el('div','catalog-tools');search.setAttribute('aria-label','Buscar comparación');tools.append(search,sort);box.append(tools);const grid=el('div','compare-grid');box.append(grid);
 function draw(){grid.replaceChildren();const groups=new Map();for(const p of [...records].sort((a,b)=>b.at.localeCompare(a.at))){if(!groups.has(p.key))groups.set(p.key,[]);groups.get(p.key).push(p);}let entries=[...groups.values()].filter(h=>h.some(p=>normalize(p.name+' '+p.store+' '+p.brand+' '+p.variant).includes(normalize(search.value))));if(sort.value==='name')entries.sort((a,b)=>a[0].name.localeCompare(b[0].name,'es'));if(!entries.length)grid.append(empty('No hay compras que coincidan con tu búsqueda.'));
 for(const h of entries){const last=h[0],card=el('article','compare-card'),heading=el('div','compare-heading');heading.append(iconNode(last.icon_key,last.emoji,'item-emoji'),el('h3','',last.name));card.append(heading,el('p','section-description',[last.brand,last.variant,last.packageSize?`${last.packageSize} ${units[last.packageUnit]} por presentación`:'',`Precio por ${units[last.unit]}`].filter(Boolean).join(' · ')),el('strong','compare-price',money(last.unitCents)),el('p','',`${last.store} · ${date(last)}`),el('p','price-change',changeText(last.unitCents,h[1]?.unitCents)));
 const latest=[...new Map([...h].reverse().map(p=>[normalize(p.store),p])).values()].sort((a,b)=>a.unitCents-b.unitCents);card.append(el('h4','','Último precio por establecimiento'));for(const p of latest){const row=el('div','store-price');row.append(el('span','',p.store),el('strong','',money(p.unitCents)),el('small','',date(p)));card.append(row);}if(latest.length>1)card.append(el('p','section-description',`Diferencia entre establecimientos: ${money(latest.at(-1).unitCents-latest[0].unitCents)}. Precios registrados en fechas distintas; no garantizan el precio actual.`));else card.append(el('p','section-description','Registra este producto en otro establecimiento para comparar.'));
 const details=el('details','purchase-history');details.append(el('summary','',`Historial · ${h.length} compras`));for(const p of h){const row=el('div','store-price');row.append(el('span','',`${date(p)} · ${p.store}`),el('strong','',`${money(p.unitCents)} / ${units[p.unit]}`),el('small','',`${p.quantity} ${units[p.unit]} · Total ${money(p.totalCents)}`));details.append(row);}card.append(details);grid.append(card);}}
 search.oninput=sort.onchange=draw;draw();
}
